FROM postgres 
COPY init.sql /docker-entrypoint-initdb.d

#from postgres told docker to build image from postgres
#postgres is the image name. We are asking docker to copy init.sql file into the docker-entrypoint-initdb folder
